version: '3'
services:
  
  webserver-time:
    container_name: time-fanap
    image: 47505495e0ee/fanap-webserver-time
    restart: always
    ports:
     - "80:80"
    networks:
      fanapnet:
        ipv4_address: 10.10.34.3
    volumes:
      - fanap-volume:/var/log/nginx/
  
  nextjs:
    container_name: nextjs-fanap
    image: 47505495e0ee/fanap-nextjs
    restart: always
    networks:
      fanapnet:
        ipv4_address: 10.10.34.2
  
networks:
  fanapnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.34.0/24
          gateway: 10.10.34.34
volumes:
  fanap-volume:
